# Generated by Django 5.1 on 2024-09-13 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='excersice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='muscle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('img', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='excersice_muscle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excersice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.excersice')),
                ('muscle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.muscle')),
            ],
        ),
        migrations.CreateModel(
            name='set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('time', models.IntegerField()),
                ('distance', models.FloatField()),
                ('notes', models.TextField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('biserie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='biserie_set', to='myapp.set')),
                ('excersice', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.excersice')),
                ('triserie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='triserie_set', to='myapp.set')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.workout')),
            ],
        ),
    ]
