# Generated by Django 5.1 on 2024-09-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='excersice',
            name='type',
            field=models.CharField(choices=[('W_R', 'Weight and Reps'), ('D_T', 'Distance and Time'), ('W_D', 'Weight and Distance'), ('W_T', 'Weight and Time'), ('R_D', 'Reps and Distance'), ('R_T', 'Reps and Time'), ('W', 'Weight'), ('R', 'Reps'), ('D', 'Distance'), ('T', 'Time')], default='W_R', max_length=3),
        ),
    ]
