# Generated by Django 5.1 on 2024-09-13 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='muscle',
            name='excersice',
            field=models.ManyToManyField(to='myapp.excersice'),
        ),
        migrations.AddField(
            model_name='workout',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='excersice_muscle',
        ),
    ]
