# Generated by Django 5.1 on 2024-09-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_workout_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='muscle',
            name='excersice',
        ),
        migrations.AddField(
            model_name='excersice',
            name='muscle',
            field=models.ManyToManyField(to='myapp.muscle'),
        ),
    ]
