# Generated by Django 5.1 on 2024-09-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_workout_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='rir',
            field=models.IntegerField(default=1),
        ),
    ]
