# Generated by Django 5.1 on 2024-09-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_set_rir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excersice',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='muscle',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
