# Generated by Django 5.1 on 2024-09-18 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_workout_date_workout_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='excersice',
            new_name='exersice',
        ),
        migrations.RenameField(
            model_name='setgroup',
            old_name='excersice',
            new_name='exersice',
        ),
        migrations.AlterField(
            model_name='workout',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
