# Generated by Django 5.1 on 2024-09-18 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_excersice_exersice_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='exersice',
            new_name='exercise',
        ),
        migrations.RenameField(
            model_name='setgroup',
            old_name='exersice',
            new_name='exercise',
        ),
    ]
