# Generated by Django 5.1 on 2024-09-21 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_exersice_exercise_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='setgroup',
            unique_together=set(),
        ),
    ]
