# Generated by Django 5.1 on 2024-10-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_setgroup_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='date',
        ),
        migrations.AddField(
            model_name='set',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
