# Generated by Django 5.1 on 2024-10-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_set_date_set_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='setgroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
